<?php

namespace Tests\Feature;

use App\Models\Room;
use App\Models\RoomSlugHistory;
use App\Models\User;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class RoomSlugApiTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();
        $this->withoutMiddleware(ValidateCsrfToken::class);
    }

    /**
     * @return array<string, string>
     */
    private function statefulHeaders(): array
    {
        return ['Referer' => config('app.url')];
    }

    public function test_list_rooms_includes_slug(): void
    {
        $guest = User::factory()->guest()->create();
        $room = Room::query()->create([
            'room_name' => 'Тест UA',
            'topic' => null,
            'access' => Room::ACCESS_PUBLIC,
        ]);

        $this->from(config('app.url'))
            ->actingAs($guest, 'web')
            ->withHeaders($this->statefulHeaders())
            ->getJson('/api/v1/rooms')
            ->assertOk()
            ->assertJsonPath('data.0.slug', $room->fresh()->slug);
    }

    public function test_messages_resolve_by_slug(): void
    {
        $guest = User::factory()->guest()->create();
        $room = Room::query()->create([
            'room_name' => 'Public X',
            'topic' => null,
            'access' => Room::ACCESS_PUBLIC,
        ]);
        $slug = $room->fresh()->slug;

        $this->from(config('app.url'))
            ->actingAs($guest, 'web')
            ->withHeaders($this->statefulHeaders())
            ->getJson('/api/v1/rooms/'.$slug.'/messages')
            ->assertOk();
    }

    public function test_messages_resolve_by_old_slug_after_rename(): void
    {
        $user = User::factory()->create();
        $room = Room::query()->create([
            'room_name' => 'Alpha',
            'topic' => null,
            'access' => Room::ACCESS_PUBLIC,
            'created_by_user_id' => $user->id,
        ]);
        $oldSlug = $room->fresh()->slug;

        $this->from(config('app.url'))
            ->actingAs($user, 'web')
            ->withHeaders($this->statefulHeaders())
            ->patchJson('/api/v1/rooms/'.$room->room_id, ['room_name' => 'Beta'])
            ->assertOk();

        $room->refresh();
        $this->assertNotSame($oldSlug, $room->slug);
        $this->assertTrue(RoomSlugHistory::query()->where('slug', $oldSlug)->exists());

        $this->from(config('app.url'))
            ->actingAs($user, 'web')
            ->withHeaders($this->statefulHeaders())
            ->getJson('/api/v1/rooms/'.$oldSlug.'/messages')
            ->assertOk()
            ->assertJsonPath('meta.slug_redirect', true);
    }

    public function test_create_room_rejects_reserved_slug(): void
    {
        $user = User::factory()->vip()->create();
        \App\Models\ChatSetting::query()->update([
            'room_create_min_public_messages' => 0,
            'public_message_count_scope' => \App\Models\ChatSetting::SCOPE_ALL_PUBLIC_ROOMS,
            'message_count_room_id' => null,
        ]);

        $this->from(config('app.url'))
            ->actingAs($user, 'web')
            ->withHeaders($this->statefulHeaders())
            ->postJson('/api/v1/rooms', [
                'room_name' => 'My Room',
                'slug' => 'admin',
            ])
            ->assertStatus(422)
            ->assertJsonValidationErrors(['slug']);
    }

    public function test_autogenerated_slug_avoids_reserved_admin(): void
    {
        $user = User::factory()->vip()->create();
        \App\Models\ChatSetting::query()->update([
            'room_create_min_public_messages' => 0,
            'public_message_count_scope' => \App\Models\ChatSetting::SCOPE_ALL_PUBLIC_ROOMS,
            'message_count_room_id' => null,
        ]);

        $this->from(config('app.url'))
            ->actingAs($user, 'web')
            ->withHeaders($this->statefulHeaders())
            ->postJson('/api/v1/rooms', [
                'room_name' => 'Admin',
            ])
            ->assertCreated();

        $slug = Room::query()->orderByDesc('room_id')->value('slug');
        $this->assertNotSame('admin', $slug);
        $this->assertStringStartsWith('admin', (string) $slug);
    }
}
